### ISSUE TITLE
Error in PagerDuty.java file

### ISSUE THREAD

**Issue by pontiyaraja** [square/pagerduty-incidents#12]
Hi, 
      I try to use pagerduty sample jar, but i am getting the following error

ava.lang.NoClassDefFoundError: retrofit/RestAdapter$Builder
	at com.squareup.pagerduty.incidents.PagerDuty.create(PagerDuty.java:30)

I think RestAdapter class is missing or imported path is wrong.

**Comment by JakeWharton** [comment]
You need to also include Retrofit 1.9.0 and Gson 2.3.1 which are dependencies of this library.
