### ISSUE TITLE
Exception within PagerDuty Client caused by accessing a private Method in Gson

### ISSUE THREAD

**Issue by orangecoding** [square/pagerduty-incidents#19]
Hi.
We use the PagerDuty Java Client to connect to your service. Now we are forced to update our Client as the old one stoped working with your API for some reason. We tried to upgrade to v 2.0.0. Afterwards we'll get the following exception each time we try to push an incident.

``` java
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.gson.Gson.newJsonWriter(Ljava/io/Writer;)Lcom/google/gson/stream/JsonWriter; from class retrofit2.converter.gson.GsonRequestBodyConverter
    at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:45)
    at retrofit2.converter.gson.GsonRequestBodyConverter.convert(GsonRequestBodyConverter.java:30)
    at retrofit2.ParameterHandler$Body.apply(ParameterHandler.java:284)
    at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:108)
    at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:162)
    at com.squareup.pagerduty.incidents.PagerDuty$1.notify(PagerDuty.java:49)
```

If I'm correct,  in `GSonRequestBodyConverter#45` you try to access a method from Gson which actually is a private Method...

I've digged a bit deeper, and the problem seems to be here:
`https://github.com/square/retrofit/blob/master/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonRequestBodyConverter.java#L45`

**Comment by orangecoding** [comment]
Mhm.. Problem seems to lay here:
`https://github.com/square/retrofit/blob/master/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonRequestBodyConverter.java#L45`

**Comment by orangecoding** [comment]
By the way, the older client (1.1.1) doesn't work anymore as it simply throws an HTTP 400.

```Java
retrofit.RetrofitError: 400 Bad Request
	at retrofit.RetrofitError.httpError(RetrofitError.java:39)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:382)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.squareup.pagerduty.incidents.$Proxy0.notify(Unknown Source)
	at com.squareup.pagerduty.incidents.PagerDuty$1.notify(PagerDuty.java:47)
```

Seems to me like you guys have changed your API or something. Is there any document you track changes like these which we can use to be prepared for something like this?

**Comment by JakeWharton** [comment]
That method is public in the version of Gson Retrofit depends on. Is an
older version of Gson being used in your application?

**Comment by orangecoding** [comment]
No, we actually don't use Gson within our code, but in your own pom.xml, you refrerence this:
```java
 <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.3.1</version>
    </dependency>
```
retrofit wants Gson 2.6.1

**Comment by orangecoding** [comment]
Ok, I've got it working now. The problem is due to the mismatch of Gson Versions used within retrofit and PagerDuty Java Client.
I've added Gson v 2.6.1 and excluded your old pom like so:
```java
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.6.1</version>
    </dependency>
    <dependency>
      <groupId>com.squareup.pagerduty</groupId>
      <artifactId>pagerduty-incidents</artifactId>
      <version>2.0.0</version>
      <exclusions>
        <exclusion>
          <artifactId>gson</artifactId>
          <groupId>com.google.code.gson</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```
This worked, so I've added a pullreq. where I've increased the Gson version.

**Comment by orangecoding** [comment]
Mhm... For some reason, now trying to use pagerDuty now, the Result is always null...

```java
public class PagerDutyTest {

  public static void main(String[] args) {
    PagerDuty pagerDutyClient = PagerDuty.create("SOME KEY");
    try {

      Trigger trigger = new Trigger.Builder("Sync responded with code: ").build();
      NotifyResult result = pagerDutyClient.notify(trigger);
      System.out.printf(result.status());//this is always null!
      System.out.println("DONE");
    }catch(Exception e){
      e.printStackTrace();
    }
  }
}```

**Comment by orangecoding** [comment]
Doing the test from above, I'll ```RealCall.java#59```I'll get a response with status Code 400 Bad request...

```Response{protocol=http/1.1, code=400, message=Bad Request, url=https://events.pagerduty.com/generic/2010-04-15/create_event.json}```

**Comment by JakeWharton** [comment]
I don't have time to look right now, but I can during the week. Thanks for the report.

**Comment by orangecoding** [comment]
Ok, I've got it working now, API Key was wrong. Anyways, it would be nice if you guys would throw up an error. There was nothing and I had to debug the whole stuff to find out I was using the API key where it should be the service key...

Ok, could you guys tell me when you'll release a v2.0.1 with the fixed pom as this is important for us..

**Comment by vschafer** [comment]
It seems that any error returned from PagerDuty is not reported back to the caller as an Exception, but only manifests itself as null NotifyResult object returned from the call. This behavior is different from 1.x which was throwing exceptions and I would consider it a bug.

**Comment by joellundell** [comment]
Hi @JakeWharton! 

Did you have time to look at the issue? We're experiencing it as well and it's hard to figure out what the actual error is since all we get back is a null.

Thank you,
Joel

**Comment by lwoodson** [comment]
Have encountered all of these same issues.  To add, the integration test no longer works https://github.com/square/pagerduty-incidents/blob/pagerduty-incidents-2.0.0/src/test/java/com/squareup/pagerduty/incidents/PagerDutyIT.java and fails with an NPE as described above.

I am going to see about fixing the issues in a fork and will issue a PR back.

**Comment by lwoodson** [comment]
Details of errors when running that integration test.  The value for service_key is being set to the api_key in some way that is not readily apparent.

```
--> POST https://events.pagerduty.com/generic/2010-04-15/create_event.json http/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 111

{"service_key":"REDACTED","event_type":"trigger","description":"Client IT trigger #1","details":{}}
--> END POST (111-byte body)
<-- 400 Bad Request https://events.pagerduty.com/generic/2010-04-15/create_event.json (1540ms)
Server: nginx
Date: Wed, 14 Sep 2016 14:36:58 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
OkHttp-Sent-Millis: 1473863818416
OkHttp-Received-Millis: 1473863818506

{"status":"invalid event","message":"Event object is invalid","errors":["Service key is the wrong length (should be 32 characters)"]}
```

The PR will get this test working and add support for building Triggers/Resolutions with a service key.  I may include runtime exceptions encapsulating errors from the HTTP calls if its something easy to implement.  If not, I still think it should be done, but it might be in a separate PR.

**Comment by lwoodson** [comment]
Added this PR that partly addresses the issue https://github.com/square/pagerduty-incidents/pull/24

**Comment by bbeaudreault** [comment]
What's the status of this? Open and no comments for a year and a half but still an active issue.
